---
name: Debian Packages
on: 
  push: {}
  pull_request: {}
jobs:
  Create-Debian-Packages:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install dependencies"
        run: "apt update && apt full-upgrade -y && apt install -y devscripts equivs build-essential"
      - name: "Install additional package build dependencies"
        run: "mk-build-deps -ir"
      - name: "Build .debs"
        run: "debuild -i -us -uc -b && mv ../*.deb ./"
      - name: "Archive"
        uses: "actions/upload-artifact@v3"
        with:
          name: "Debian Packages"
          path: |
            *.deb
