---
name: "Debian Packages"
on:
  pull_request: {}
jobs:
  Create-Debian-Packages:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Install dependencies"
        run: "sudo apt update && sudo apt full-upgrade -y && sudo apt install -y devscripts equivs build-essential"
      - name: "Install additional package build dependencies"
        run: "sudo mk-build-deps -ir"
      - name: "Build .debs"
        run: "debuild -i -us -uc -b && mv ../*.deb ./"
      - name: "Archive"
        uses: "actions/upload-artifact@v3"
        with:
          name: "Debian Packages"
          path: |
            *.deb
